# Generated by Django 5.0.6 on 2024-07-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_password1_memberform_confirm_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberForm',
        ),
    ]
