# Generated by Django 5.0.6 on 2024-07-23 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_poll_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
